name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Deploy Script file
        working-directory: ./
        run: ./deploy-action.sh
        env:
          SSH_KEY_2022_08_17: ${{ secrets.SSH_KEY_2022_08_17 }}

     